### ISSUE TITLE
Use cases & suggestions

### ISSUE THREAD

**Issue by jankeromnes** [La0/mozilla-static-analysis#1]
Thanks a lot for working on this dashboard!

I see it being useful to our team in the following ways:

- See recent reviews published to MozReview or Phabricator (to see how the bot behaves in the wild / if the reviews it publishes look useful)
- Get a feeling for how many defects we are catching before they land in Firefox (i.e. assess our bot's usefulness)
- Filter by defect type in order to understand the usefulness of each checker (e.g. do we usually find many `performance-faster-string-find`s in patches? Are they published or not? Are developers ignoring `modernize-raw-string-literal`s? How many security or performance defects do we catch, and are they getting fixed? etc.)
- Find a problematic review to investigate (e.g. a user files an issue; I see the problem in the review; I find it in the dashboard; I look at the task's logs / raw tool outputs / report.json to understand the bug)
- Keep an eye on `staging` results when we try new things (e.g. enabling `BEFORE_AFTER`, or new linters/checkers like `clang-format`, etc.)

Here are a few suggestions to fully enable the above use cases:

- [x] Indicate whether the reviews are from `testing`, `staging` or `release` (and maybe toggle between them with a dropdown in the menu bar?)
- [ ] Show *published* issues instead of *all* issues in a review (I mostly care if a review has published *any* comments, not if it found 0 or 300 unreported problems)
  - [ ] and maybe allow filtering out analysis runs that have 0 published issues? (They're interesting to dig into, looking for new potentially publishable defects, but most of the time you want to review comments that *were* actually published)
- [ ] Allow searching/filtering by review ID or bug number (e.g. "show me all reviews of bug 123456"); or by defect type (e.g. "show me all reviews with `modernize-shrink-to-fit` defects in them")

**Comment by La0** [comment]
The channel (only testing has data now) is displayed on the navbar. I was planning on creating an option to switch channels.

On the details page, publishable issues count is already displayed just to the right of the total count. I can switch their places to increase readability, but both infos are useful.
I can add the info to the list by patching the bot.

Filtering & searching are the big next dev i'm planning, thanks for the feedback Jan

**Comment by La0** [comment]
[Splitted and moved](https://github.com/mozilla/release-services/issues/1390)
