### ISSUE TITLE
Please move to a moz.tools domain

### ISSUE THREAD

**Issue by sylvestre** [La0/mozilla-static-analysis#10]
The title says all!

**Comment by La0** [comment]
Yes, i'd like to do that using services.

@sylvestre Do you have a preferred domain name ? `sa.moz.tools` ?

**Comment by sylvestre** [comment]
reviewbot.moz.tools ?
depending if we keep the name.
cc @jankeromnes

**Comment by jankeromnes** [comment]
I'm fine with:

- `analysis.moz.tools` (I thought we weren't supposed to say "static" anymore, but I forgot why)
- `reviewbot.moz.tools`

or similar name (but please use full words instead of acronyms).

**Comment by La0** [comment]
[Done](https://static-analysis.staging.moz.tools)
