### ISSUE TITLE
The statistic page is failing

### ISSUE THREAD

**Issue by sylvestre** [La0/mozilla-static-analysis#14]
https://static-analysis.staging.moz.tools/#/stats

> Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à https://taskcluster-artifacts.net/BB56vwm8TUK-uFgByTES8Q/0/public/results/report.json (« connect-src »).

**Comment by La0** [comment]
Moved this issue on [mozilla/release-services](https://github.com/mozilla/release-services/issues/1388)
