### ISSUE TITLE
Please use the desc instead of the flake8 code

### ISSUE THREAD

**Issue by sylvestre** [La0/mozilla-static-analysis#7]
F821 isn't super useful
![image](https://user-images.githubusercontent.com/733326/42766184-0ffab2b0-891a-11e8-9426-1b6cbab96672.png)

**Comment by La0** [comment]
I can use data from [this list](http://flake8.pycqa.org/en/latest/user/error-codes.html) to provide this information. Would that be OK ?

**Comment by sylvestre** [comment]
I think we have the information at review phase?

**Comment by La0** [comment]
Yes but it's not generic (variable names are used), so i can't really make anything of it for the stats.

For **F821**, i would have some issues with `undefined name myVariable`, then `undefined name xxx`, and so on...
