### ISSUE TITLE
Please add a timespan

### ISSUE THREAD

**Issue by sylvestre** [La0/mozilla-static-analysis#8]
https://nextcairn.com/mozilla-sa/#/stats
"Loaded 107/107 tasks" doesn't say much.
Having "since 3 days" would be great and good enough!

**Comment by La0** [comment]
Done.
![screen](https://screenshotscdn.firefoxusercontent.com/images/4ac48340-7fb5-4ea3-8827-5a6d9bfa44e5.png)

**Comment by sylvestre** [comment]
You rock, merci!
