### ISSUE TITLE
Dashboard is lying about a published element

### ISSUE THREAD

**Issue by sylvestre** [La0/mozilla-static-analysis#9]
The dashboard says that it found and published a clang analyzer issue:
![image](https://user-images.githubusercontent.com/733326/42865460-fc062ffe-8a69-11e8-8a5e-158f4f0da8a2.png)

It points to:
https://nextcairn.com/mozilla-sa/#/check/clang-tidy.clang-analyzer-deadcode.DeadStores
Which links to
https://reviewboard.mozilla.org/r/256212/ (see also https://bugzilla.mozilla.org/show_bug.cgi?id=1447945)
which doesn't show any activity from the bot.

**Comment by La0** [comment]
You are looking at data from testing or staging, it did not reach production yet. Hence no publication on mozreview or phabricator
